{
  "openapi": "3.0.3",
  "info": {
    "title": "RMS Services API Reference",
    "summary": "This document provides a comprehensive reference guide for the RMS Services API. The RMS Services API is a set of RESTful endpoints that allow developers to programmatically interact with RMS Services. This document includes detailed descriptions of each available endpoint, as well as the parameters, methods, and data structures used by the API.",
    "description": "Copyright: Â© Keture 2023. All rights reserved. This API reference is provided solely for the purpose of development and testing. Any commercial use or redistribution of this API, or any part thereof, is strictly prohibited without the prior written consent of Keture.",
    "version": "1.0.1"
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "apiKey",

        "name": "Authorization",

        "in": "header"
      }
    },

    "schemas": {}
  },
  "definitions": {},
  "paths": {
    "/api/v1/cv/upload": {
      "post": {
        "tags": ["Test"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["cv"],
                "properties": {
                  "cv": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              },
              "example": {
                "cv": "file_contents_here"
              }
            }
          },
          "required": true
        },
        "consumes": ["multipart/form-data"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "CV Uploaded",
            "content": {
              "application/json": {
                "example": {
                  "message": "CV uploaded successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/admin/department": {
      "get": {
        "tags": ["Admin"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/admin/department/": {
      "post": {
        "tags": ["Admin"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["name"],
                "properties": {
                  "name": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "Sales"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      },
      "put": {
        "tags": ["Admin"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["name", "id"],
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "name": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "id": 123,
                "name": "Engneering"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      },
      "delete": {
        "tags": ["Admin"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["id"],
                "properties": {
                  "id": {
                    "type": "integer"
                  }
                }
              },
              "example": {
                "id": 123
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/admin/department/{id}": {
      "get": {
        "tags": ["Admin"],
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "required": true,
            "in": "path",
            "name": "id"
          },
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/admin/job_type": {
      "get": {
        "tags": ["Admin"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/admin/job_type/": {
      "post": {
        "tags": ["Admin"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["name"],
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "Full-time",
                "description": "A full-time permanent job."
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Job type Created",
            "content": {
              "application/json": {
                "example": {
                  "id": 123,
                  "name": "Full-time",
                  "description": "A full-time permanent job."
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Admin"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["name", "id"],
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "id": 123,
                "name": "Part-time",
                "description": "A part-time temporary job."
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Job type Updated",
            "content": {
              "application/json": {
                "example": {
                  "id": 123,
                  "name": "Part-time",
                  "description": "A part-time temporary job."
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Admin"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["id"],
                "properties": {
                  "id": {
                    "type": "integer"
                  }
                }
              },
              "example": {
                "id": 123
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Job type Deleted",
            "content": {
              "application/json": {
                "example": {
                  "message": "Job type with id 123 was deleted successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/admin/job_type/{id}": {
      "get": {
        "tags": ["Admin"],
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "required": true,
            "in": "path",
            "name": "id"
          },
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/admin/work_style": {
      "get": {
        "tags": ["Admin"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/admin/work_style/": {
      "post": {
        "tags": ["Admin"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["name"],
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "Remote",
                "description": "Ability to work remotely."
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Work Style Created",
            "content": {
              "application/json": {
                "example": {
                  "id": 123,
                  "name": "Remote",
                  "description": "Ability to work remotely."
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Admin"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["name", "id"],
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "id": 123,
                "name": "Hybrid",
                "description": "Combination of office and remote work."
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Work Style Updated",
            "content": {
              "application/json": {
                "example": {
                  "id": 123,
                  "name": "Hybrid",
                  "description": "Combination of office and remote work."
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Admin"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["id"],
                "properties": {
                  "id": {
                    "type": "integer"
                  }
                }
              },
              "example": {
                "id": "123"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Work Style Deleted",
            "content": {
              "application/json": {
                "example": {
                  "message": "Work style with id 123 was deleted successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/admin/work_style/{id}": {
      "get": {
        "tags": ["Admin"],
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "required": true,
            "in": "path",
            "name": "id"
          },

          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/admin/job_level": {
      "get": {
        "tags": ["Admin"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/admin/job_level/": {
      "post": {
        "tags": ["Admin"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["name"],
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "Entry",
                "description": "Beginner or junior level job."
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Job Level Created",
            "content": {
              "application/json": {
                "example": {
                  "id": 123,
                  "name": "Entry",
                  "description": "Beginner or junior level job."
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Admin"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["name", "id"],
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "id": 123,
                "name": "Mid",
                "description": "Intermediate level job."
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Job Level Updated",
            "content": {
              "application/json": {
                "example": {
                  "id": 123,
                  "name": "Mid",
                  "description": "Intermediate level job."
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Admin"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["id"],
                "properties": {
                  "id": {
                    "type": "integer"
                  }
                }
              },
              "example": {
                "id": 123
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Job Level Deleted",
            "content": {
              "application/json": {
                "example": {
                  "message": "Job level with id 123 was deleted successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/admin/job_level/{id}": {
      "get": {
        "tags": ["Admin"],
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "required": true,
            "in": "path",
            "name": "id"
          },

          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/jobportal/application/all_apliactions": {
      "post": {
        "tags": ["Jobportal"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["start", "end"],
                "properties": {
                  "start": {
                    "type": "number"
                  },
                  "end": {
                    "type": "number"
                  }
                }
              },
              "example": {
                "start": 0,
                "end": 10
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Applications Fetched",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 123,
                    "candidateName": "John Doe"
                  },
                  {
                    "id": 456,
                    "candidateName": "Jane Doe"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/jobportal/application/": {
      "post": {
        "tags": ["Jobportal"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "fullName",
                  "email",
                  "phone",
                  "linkedIn_url",
                  "resume_file"
                ],
                "properties": {
                  "fullName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "phone": {
                    "type": "string"
                  },
                  "linkedIn_url": {
                    "type": "string"
                  },
                  "resume_file": {
                    "type": "string"
                  },
                  "candidate_id": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "fullName": "John Doe",
                "email": "john@email.com",
                "phone": "1234567890",
                "linkedIn_url": "linkedin.com/john",
                "resume_file": "resume.pdf",
                "candidate_id": "abc123"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Applications Submitted",
            "content": {
              "application/json": {
                "example": {
                  "message": "Application submitted successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/jobportal/auth/register": {
      "post": {
        "tags": ["Jobportal", "Auth"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["email", "password"],
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "first_name": {
                    "type": "string"
                  },
                  "last_name": {
                    "type": "string"
                  },
                  "phone_number": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "john@email.com",
                "password": "password123",
                "first_name": "John",
                "last_name": "Doe",
                "phone_number": "1234567890"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User Registered",
            "content": {
              "application/json": {
                "example": {
                  "message": "Registration successful"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/jobportal/auth/login": {
      "post": {
        "tags": ["Jobportal", "Auth"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["email", "password"],
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "john@email.com",
                "password": "password123"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login Successful",
            "content": {
              "application/json": {
                "example": {
                  "accessToken": "string",
                  "refreshToken": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/jobportal/auth/refresh": {
      "post": {
        "tags": ["Auth", "Jobportal"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["refresh_token"],
                "properties": {
                  "refresh_token": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "refresh_token": "string"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Token Refreshed",
            "content": {
              "application/json": {
                "example": {
                  "access_token": "string",
                  "refresh_token": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/jobportal/auth/logout": {
      "post": {
        "tags": ["Auth", "Jobportal"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["refresh_token"],
                "properties": {
                  "refresh_token": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/jobportal/job/all_jobs": {
      "post": {
        "tags": ["Jobportal"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["start", "end"],
                "properties": {
                  "start": {
                    "type": "number"
                  },
                  "end": {
                    "type": "number"
                  }
                }
              },
              "example": {
                "start": 0,
                "end": 10
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Jobs Fetched",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 123,
                    "title": "Software Engineer"
                  },
                  {
                    "id": 456,
                    "title": "Product Manager"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/jobportal/job/id": {
      "get": {
        "tags": ["Jobportal"],
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "required": true,
            "in": "path",
            "name": "id"
          },

          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/jobportal/organization/all_companies": {
      "post": {
        "tags": ["Jobportal"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["start", "end"],
                "properties": {
                  "start": {
                    "type": "number"
                  },
                  "end": {
                    "type": "number"
                  }
                }
              },
              "example": {
                "start": 0,
                "end": 10
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Companies Fetched",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 123,
                    "name": "Company A"
                  },
                  {
                    "id": 456,
                    "name": "Company B"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/jobportal/organization/{id}": {
      "get": {
        "tags": ["Jobportal"],
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "required": true,
            "in": "path",
            "name": "id"
          },

          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/jobportal/main/popular-category": {
      "get": {
        "tags": ["Jobportal"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/jobportal/main/featured-jobs": {
      "get": {
        "tags": ["Jobportal"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/jobportal/main/top-recruiters": {
      "get": {
        "tags": ["Jobportal"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/jobportal/main/counts": {
      "get": {
        "tags": ["Jobportal"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/dashboard/auth/register": {
      "post": {
        "tags": ["Dashboard"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "organization_name",
                  "organization_email",
                  "organization_category_id",
                  "first_name",
                  "last_name",
                  "email",
                  "password",
                  "phone_number"
                ],
                "properties": {
                  "organization_name": {
                    "type": "string"
                  },
                  "organization_email": {
                    "type": "string"
                  },
                  "organization_category_id": {
                    "type": "integer"
                  },
                  "first_name": {
                    "type": "string"
                  },
                  "last_name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "phone_number": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "organization_name": "Acme Inc",
                "organization_email": "contact@acme.com",
                "organization_category_id": 123,
                "first_name": "John",
                "last_name": "Doe",
                "email": "john@acme.com",
                "password": "password123",
                "phone_number": "1234567890"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Registration Successful",
            "content": {
              "application/json": {
                "example": {
                  "message": "Registered successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/dashboard/auth/login": {
      "post": {
        "tags": ["Dashboard"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["email", "password"],
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "john@acme.com",
                "password": "password123"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login Successful",
            "content": {
              "application/json": {
                "example": {
                  "accessToken": "string",
                  "refreshToken": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/dashboard/auth/refresh": {
      "post": {
        "tags": ["Dashboard"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["refresh_token"],
                "properties": {
                  "refresh_token": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "refreshToken": "string"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/dashboard/auth/logout": {
      "post": {
        "tags": ["Dashboard"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["refresh_token"],
                "properties": {
                  "refresh_token": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "refreshToken": "string"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/dashboard/job": {
      "get": {
        "tags": ["Dashboard"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/dashboard/job/add": {
      "post": {
        "tags": ["Dashboard"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["title", "department_id"],
                "properties": {
                  "department_id": {
                    "type": "integer"
                  },
                  "title": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "department_id": 123,
                "title": "Software Engineer"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Job Added",
            "content": {
              "application/json": {
                "example": {
                  "message": "Job added successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/dashboard/job/edit": {
      "post": {
        "tags": ["Dashboard"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["title", "department_id"],
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "title": {
                    "type": "string"
                  },
                  "department_id": {
                    "type": "integer"
                  }
                }
              },
              "example": {
                "department_id": 123,
                "title": "Software Engineer"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Job Added",
            "content": {
              "application/json": {
                "example": {
                  "message": "Job added successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/dashboard/job/delete": {
      "post": {
        "tags": ["Dashboard"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["id"],
                "properties": {
                  "id": {
                    "type": "integer"
                  }
                }
              },
              "example": {
                "id": 123
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/dashboard/job/{id}": {
      "get": {
        "tags": ["Dashboard"],
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "required": true,
            "in": "path",
            "name": "id"
          },

          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/seed/admin": {
      "get": {
        "tags": ["Seed"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/seed/department": {
      "get": {
        "tags": ["Seed"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/seed/job_type": {
      "get": {
        "tags": ["Seed"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/seed/job_level": {
      "get": {
        "tags": ["Seed"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/seed/roles": {
      "get": {
        "tags": ["Seed"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/seed/organization_category": {
      "get": {
        "tags": ["Seed"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/seed/work_style": {
      "get": {
        "tags": ["Seed"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/dashboard/data/department": {
      "get": {
        "tags": ["Dashboard"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/dashboard/data/job_type": {
      "get": {
        "tags": ["Dashboard"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/dashboard/data/job_level": {
      "get": {
        "tags": ["Dashboard"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/dashboard/data/organization_category": {
      "get": {
        "tags": ["Dashboard"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/dashboard/data/work_style": {
      "get": {
        "tags": ["Dashboard"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/dashboard/organization/department": {
      "get": {
        "tags": ["Dashboard"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/dashboard/organization/job_level": {
      "get": {
        "tags": ["Dashboard"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/dashboard/organization/job": {
      "get": {
        "tags": ["Dashboard"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/dashboard/organization/work_style": {
      "get": {
        "tags": ["Dashboard"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/admin/auth/logout": {
      "post": {
        "tags": ["Auth", "Admin"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["refresh_token"],
                "properties": {
                  "refresh_token": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "refresh_token": "string"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": {
                "example": {
                  "message": "Logged out successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/admin/auth/refresh": {
      "post": {
        "tags": ["Auth", "Admin"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["refresh_token"],
                "properties": {
                  "refresh_token": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "refresh_token": "string"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    },
    "/api/v1/admin/auth/login": {
      "post": {
        "tags": ["Admin", "Auth"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["email", "password"],
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "admin@example.com",
                "password": "password123"
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login Successful",
            "content": {
              "application/json": {
                "example": {
                  "accessToken": "string",
                  "refreshToken": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/seed/all": {
      "get": {
        "tags": ["Seed"],
        "parameters": [
          {
            "in": "path",
            "name": "v1",
            "required": true,
            "schema": {
              "type": "string",
              "default": "v1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response"
          }
        }
      }
    }
  },
  "host": "decho-ecsal-1u37eco2q0vd3-657960941.ap-south-1.elb.amazonaws.com",
  "schemes": ["http"],
  "tags": [
    {
      "name": "Admin",
      "description": "Admin related end-points"
    },
    {
      "name": "Auth",
      "description": "Authentication related end-points"
    },
    {
      "name": "Seed",
      "description": "Seed related end-points"
    },
    {
      "name": "Jobportal",
      "description": "Jobportal related end-points"
    },
    {
      "name": "Dashboard",
      "description": "Dashboard related end-points"
    }
  ]
}
